#!/bin/bash
#====================================================================
#====================================================================

#set -e

#====================================================================
TIMESTAMP=`date "+%Y-%m-%d-%H%M%S" `


LIMA_TMP_DIR_COMMON="Lima_tmp"
LIMA_TMP_DIR="${LIMA_TMP_DIR_COMMON}_${TIMESTAMP}"
LIMA_TMP_DIR_FULL="${LIMA_TMP_DIR}_full"

LIMA_LIMA="$HOME/lima/lima"
LIMA_PCO=${LIMA_LIMA}/camera/pco
LIMA_INST=${LIMA_LIMA}/install-cmake

BUILD_DIR=build

CONDA_ENV=limadev1


#====================================================================
#====================================================================
#                          MAIN
#====================================================================
#====================================================================

echo "------------------------------- init"
cd

# needed to execute conda activate from bash script
# https://github.com/conda/conda/issues/7980
source ~/conda/miniconda/etc/profile.d/conda.sh

conda deactivate
conda deactivate

pwd

echo "------------------------------- SISO DIR"
echo $SISODIR5

echo "------------------------------- setId"
pwd
cd ${LIMA_PCO}
./setId

echo "------------------------------- cleaning cache LIMA"
cd ${LIMA_LIMA}
pwd

rm -fr ${BUILD_DIR} ${LIMA_INST}

{
find ./ -name "CMakeCache.txt" 
find ./ -name "sip*.h"
find ./ -name "sip*.cpp"
} | xargs rm

echo "------------------------------- cleaning cache PCO"
cd ${LIMA_PCO}
pwd

rm -fr build/*

echo "------------------------------- CMAKE ALL"

(conda activate ${CONDA_ENV}; \
  cd ${LIMA_LIMA}; \
  (PREFIX=${CONDA_PREFIX} \
     SP_DIR=$(python -c "import sysconfig; print(sysconfig.get_paths().get('platlib'))") \
     bash -c '(cd third-party/Processlib && bash -e conda/debug/build.sh) && \
              (cd . && bash -e conda/debug/build.sh) && \
              (cd applications/tango/python && \
                 bash -e conda/build.sh && cp scripts/Lima* ${PREFIX}/bin) && \
              (cd camera/pco && \
                 bash -e conda/camera/build.sh && bash -e conda/tango/build.sh)'))


#==================================================================
#==================================================================
echo "------------------------------- EXIT"
exit
#==================================================================
#==================================================================


