#!/bin/bash
cmake -Bbuild -H. -GNinja -DLIMA_ENABLE_PYTHON=1 -DWITH_GIT_VERSION=1 -DCAMERA_ENABLE_TESTS=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_FIND_ROOT_PATH=$PREFIX -DPCO_INTERFACE=$SDK
cmake --build build --target install
