# Strip the 'v' from the version tag
{% if GIT_DESCRIBE_TAG is defined %}
{%   set version = GIT_DESCRIBE_TAG[1:] %}
{% else %}
{%   set version = "0.0.0" %}
{% endif %}

{% set build = environ.get('GIT_DESCRIBE_NUMBER', 0) %}

package:
  name: lima-camera-pco-tango
  version: {{ version }}

source:
  path: ../..

build:
  number: {{ build }}
  string: {{ iface }}_h{{ PKG_HASH }}_{{ build }}
  noarch: python

requirements:
  build:
    - cmake
    - ninja
    - lima-core
  run:
    - lima-tango-server
    - lima-camera-pco=*={{ iface }}*

about:
  home: https://github.com/esrf-bliss/Lima
  license: GPL
  license_file: COPYING
  summary: a library for the unified control of 2D detectors
